### PR TITLE
Initial load all scopes

### PR DESCRIPTION
**Pull request by kmarinushkin**
We earlier discussed, that i could start work with  ITR, by separating calculations of aggregate scope S1S2 into S1 and S2.
And that's what i started. However, i soon discovered, that this task is too big, to be a single step:

* the scope of required changes is wide, touching almost all ITR modules
* there is a mismatch between how a list of scopes is handled in ITR_UI, interfaces and base_providers

So, i suggest to look at the task as an "epic", to support all available separate scopes S1, S2, S3. Then, we divide this "epic" into smaller tasks, each implemented by it's own PR.

This is the first PR under this concept. It adds support for loading all available scopes from file into company_info

### CODE REVIEW

**Comment by kmarinushkin** [comment]
Hello @MichaelTiemannOSC,

please join the review, and add team members, who you think will be interested.
The path, which i chose for approaching our scopes support goal, is just a proposal. I am open for discussions

**Comment by kmarinushkin** [comment]
@MichaelTiemannOSC if we are not ready to merge this PR into `develop` branch - could you create a feature branch for me, and i will merge my scopes work into it, one PR after another?

**Comment by MichaelTiemannOSC** [comment]
These changes look like they will be a big help toward evaluating the S3 data for Automobiles, and I plan to test them in that context.  I've invited @joriscram and @dp90 to review.  @kmarinushkin if you accept the GitHub membership invitation I sent you, you, too can directly invite people to review your changes.

**Comment by MichaelTiemannOSC** [comment]
@kmarinushkin after doing a lot more work on Autos and Oil & Gas, and after evaluating the changes I've made with and without the changes you have made, it now looks to me like this is not as productive a path as I first thought.  Your changes went in the direction I asked, but having looked farther down that road, I think it's best to change direction slightly.  We can discuss when you return.

**Comment by kmarinushkin** [comment]
Sure, no problems! I am glad to see, that developing and reviewing in small PRs saved us efforts, which we would do in the wrong direction otherwise

**Comment by kmarinushkin** [comment]
This PR is outdated: the Team priorities work with S3 scope, as more S3 data is reported recently, and uncovered certain S3 gaps in the OECM methodology.
This PR is oriented on separate S1 and S2 load, which is off the table for now.

Therefore, I decline this PR. I may re-open it in future, when it's content becomes more valuable for the ITR tool.

**Pull request closed without merging**
