### PR TITLE
Refactor code to resolve mypy errors

### PR DESCRIPTION
**Pull request by MichaelTiemannOSC**
It turns out that several of the enhancements added to the Base DataProvider classes and also used by the DataWarehouse revealed many violations of proper data abstraction.  These changes refactor data structures and methods related to Company data, Production benchmarks, and Emissions Intensity benchmarks while also passing mypy scrutiny.

Moreover, from mypy's perspective, it's an anti-pattern to use None as an empty value.  Rather, there should be strongly typed empty values (which were don't for Aggregation and friends, but need to be done more generally throughout).

Because these changes were made all at once and relatively rapidly, it's quite likely we will want to continue evolving them until we are happy with names, interfaces, and overall behavior.

Vault Providers in particular is going to need work to get back up to scratch.

Starting with this as a Draft pull request because I haven't yet tested against ITR-examples, but want to give all y'all a preview as I do...

### CODE REVIEW

**Comment by MichaelTiemannOSC** [comment]
I think that before I merge this PR I'm going to take one or two more swings at replacing None as a synonym for an empty object.  That will allow me to remove many `#type: ignore` comments.

**Review by ModeSevenIndustrialSolutions — APPROVED** [review]
This looks like a great first attempt at addressing a bunch of structural and syntactical issues with the existing code!

**Comment by MichaelTiemannOSC** [comment]
Another good-sized slog of work done.  The last thing (which I plan to do tomorrow) is to true up the vault-providers code.  Since we don't have automated testing for that, I have to test it manually.  I'll do that tomorrow (and fix what needs to be fixed).

**Comment by MichaelTiemannOSC** [comment]
This version of ITR implements breaking changes.  There is a mypy-refactor branch in ITR-examples that works with these breaking changes.  Both should release together with updated version requirements clearly updated.

**Pull request merged**
